# OracleDB connection settings
spring.datasource.url=jdbc:oracle:thin:@//{{oracledb.ip:1521}}/{{SID}}
spring.datasource.username={{username}}
spring.datasource.password={{password}}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.format_sql=true

# HikariCP settings
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPoolEngine

#logging.level.root=warn
#logging.level.org.springframework=info
#logging.level.org.hibernate=info
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

server.port=9990
spring.profiles.active=development

#Redis Connection
spring.data.redis.host={{redis.ip}}
spring.data.redis.port=6379

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={{username}}
spring.mail.password={{password}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true